import Head from "next/head";
import AboutUs from "../components/AboutUs";
import Artistas from "../components/Artistas";
import Banner from "../components/Banner";
import Testimonials from "../components/Testimonials";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-r from-gray-900 via-gray-700 to-gray-900 px-5">
        <Banner />
        <Artistas />
        <Testimonials />
        <AboutUs />
      </main>
    </div>
  );
}
